### ISSUE TITLE
Check random function actually works with int division

### ISSUE THREAD

**Issue by forgetso** [prosopo/protocol#31]
In `get_random_number` we are ignoring the remainder in division:

`((rng.next_u64() / u64::MAX) * (max - min) + min) as u64`

This task is to check this function actually makes sense when using int division only.

**Comment by goastler** [comment]
it does not work.

https://github.com/prosopo/protocol/blob/027eb4e1c1da1d8fdec0928f8a4eec09f0f81edb/contracts/lib.rs#L1320

This line does integer division. The random number chosen before this line will range between u64:MIN and u64:MAX. Only when it is equal to u64:MAX (which is an incredibly unlikely event) would u64:MAX / u64:MAX == 1. This is the only time the division operation produces anything other than 0, because numbers <u64:MAX integer divide to 0.

This issue stems from the lack of floating point computation in the smart contract. We must change the division operation to use only integer based arithmetic. I will look into this now
